version: "3.4"

networks:
  tailscalenet:
    external: false

services:
  tailscale:
    image: tailscale/tailscale:v1.44.0
    container_name: tailscale
    environment:
      - TZ=Asia/Shanghai
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--login-server=https://${domain}:${port} --accept-routes=true --accept-dns=true
      - TS_TAILSCALED_EXTRA_ARGS=--tun=tailscale0 --no-logs-no-support
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      #- TS_USERSPACE=tailscale0
      #- TS_ACCEPT_DNS=true
      #- TS_NO_LOGS_NO_SUPPORT=true
      #- TS_SOCKS5_SERVER=:1055
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./config:/var/lib/tailscale
      - ./run:/var/run/tailscale
      #- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    networks:
      - tailscalenet
    #network_mode: host
    #privileged: true
    #extra_hosts:
    #  - "domain:127.0.0.1"
  tailscale-derp-server:
    container_name: tailscale-derp-server
    image: tkaxv7s/tailscale-derp-server:latest
    environment:
      - TZ=Asia/Shanghai
      - DERP_ADDR=:443    #:port or ip:port or [ip]:port
      - DERP_HTTP_PORT=80
      - DERP_STUN_PORT=3478
      - DERP_HOST=127.0.0.1    #domain or ip
      - DERP_VERIFY_CLIENTS=true
    restart: always
    volumes:
      - ./derp/certs:/app/certs
      - ./run:/var/run/tailscale
    ports:
      - "443:443"    #derp port
      - "3478:3478/udp"    #derp stun port
    networks:
      - tailscalenet
    depends_on:
      - tailscale