name: Release Docker

on:
  workflow_dispatch:

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Checkout Tailscale
        uses: actions/checkout@v3
        with:
          repository: tailscale/tailscale
          ref: main
          fetch-depth: 0
          path: tailscale

      - name: modify
        run: |
          sed -i '/hi.ServerName != m.hostname/,+2d' tailscale/cmd/derper/cert.go

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          #platforms: linux/amd64, linux/arm64, linux/arm/v7
          platforms: linux/amd64
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tailscale-derp-server:latest